<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bas</string>
		<string>basic</string>
		<string>cbs</string>
	</array>
	<key>name</key>
	<string>Color BASIC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?i:(\bREM\b|').*)</string>
			<key>name</key>
			<string>comment.line.color-basic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(AND|EQV|IMP|NOT|OR|XOR)\b)</string>
			<key>name</key>
			<string>keyword.operator.logical.color-basic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|\-|\*|\=|<>|<|>|\\|<=|>=</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.color-basic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.color-basic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.color-basic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.color-basic</string>
		</dict>
		<dict>
			<key>match</key>			
			<string>(ABS|ASC|ATN|BRK|BUTTON|CINT|COS|CSNG|D2R|EOF|EXP|FIX|INSTR|INT|LEN|LIN|LOG|MEM|NINT|NUM|PEEK|POS|REC|RND|SGN|SIN|SQR|STR\$|SYS|TH\_EXEC|TH\_HASADMIN|TH\_HASBADGE|TH\_HASLOGIN|TH\_HASROOT|TH\_SYSLEVEL|TH\_TIME|TAN|TIM\(|TIMER|USR|VAL)|(ARG\$|ARGC\%|ARGV\$|BIN\$|CHR\$|DATE\$|DIR\$|INKEY\$|HEX\$|LEFT\$|MID\$|OCT\$|POLKEY\$|PORT\%|PPPDIR\$|RIGHT\$|SPA|SPACE\$|SPC\$|STRING\$|TH\_B64D\$|TH\_B64E\$|TH\_DEFGROUP\$|TH\_GMTIME\$|TH\_HOSTNAME\$|TH\_LOCALTIME\$|TH\_MD5BASE64\$|TH\_MD5HEX\$|TH\_MODEM\$|TH\_NETSTAT\$|TH\_PLAN\$|TH\_RE\$?|TH\_REV\$|TH\_SED\$|TIME\$|UPS\$|USER\$)\B</string>
			<key>name</key>
			<string>entity.name.function.color-basic</string>
		</dict>
		<dict>
			<key>match</key>			
			<string>(AS ?#|ATTR|AUDIO|BEEP|CLEAR|CLOSE#|CLOSE ?#|CLS|COLOR|CONT|DATA|DIM|DRAW|DEF ?FN|DEFINT|EDIT|END|EXEC|FOR\s|FRE|GOSUB|GOTO|HEIGHT|HOME|IF|INPUT|LET|LINE ?INPUT|LINE|LIST|LLIST|LOCATE|MOD|MOTOR|NEW|NEXT|ON ?BRK|ON ?ERR|ON|OPEN|PAINT|PALETTE|PCLEAR|PCLS|PCOPY|PLAY|PMODE|POKE|PRESET|PRINT ?TAB|PRINT ?USING|PRINT|PUT|READ|RENUM|RESTORE|RETURN|RUN|SCRATCH|SCREEN|SET|SLEEP|SOUND|STOP|SYSTEM|TROFF|TRON|WIDTH|THEN|TO\s|STOP|DO\s|ELSE|GOTO|STEP)</string>
			<key>name</key>
			<string>keyword.control.color-basic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^([0-6][0-3][0-9][0-9][0-9]|[0-9]{1,5}) *</string>
			<key>name</key>
			<string>line.numbers.color-basic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-?[0-9]+</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-?(\&amp;H)[0-9a-fA-F]{1,7}</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-?(\&amp;O)[1-7]</string>
			<key>name</key>
			<string>constant.numeric.oct</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.color-basic</string>
	<key>uuid</key>
	<string>a0878539-eb9b-4f8a-814b-c287384503d0</string>
</dict>
</plist>
